apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pingu
  name: pingu
spec:
  containers:
  - image: nginx
    name: pingu
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
